# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: "OpenDAC: ODAC23"
short_description: Using AI to discover new sorbents to lower the cost of direct air capture.
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo_odac.png
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: ODAC23 Leaderboard
evaluation_script: evaluation_script/main.py
remote_evaluation: True
is_docker_based: False
start_date: 2023-11-29 00:00:00
end_date: 2042-12-31 23:59:59
blocked_email_domains: ["mailinator.com"]
published: False

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Energy MAE (eV) -- ID", "Forces MAE (eV / A) -- ID", "EFwT -- ID", "Energy MAE (eV) -- OOD-B", "Forces MAE (eV / A) -- OOD-B", "EFwT -- OOD-B", "Energy MAE (eV) -- OOD-L", "Forces MAE (eV / A) -- OOD-L", "EFwT -- OOD-L", "Energy MAE (eV) -- OOD-T", "Forces MAE (eV / A) -- OOD-T", "EFwT -- OOD-T", "Energy MAE (eV) -- OOD-LT", "Forces MAE (eV / A) -- OOD-LT", "EFwT -- OOD-LT"],
        "default_order_by": "EFwT -- OOD-LT",
        "metadata": {},
      }
  - id: 2
    schema:
      {
        "labels": ["Energy MAE (eV) -- ID", "EwT -- ID", "Energy MAE (eV) -- OOD-B", "EwT -- OOD-B", "Energy MAE (eV) -- OOD-L", "EwT -- OOD-L", "Energy MAE (eV) -- OOD-T", "EwT -- OOD-T", "Energy MAE (eV) -- OOD-LT", "EwT -- OOD-LT"],
        "default_order_by": "EwT -- OOD-LT",
        "metadata": {},
      }

challenge_phases:
  - id: 1
    name: Predicting energy and forces from structure (S2EF) -- Validation
    description: templates/challenge_phase_1_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: False
    start_date: 2023-11-29 00:00:00
    end_date: 2042-12-31 23:59:59
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: s2ef_val
    max_submissions_per_day: 10
    max_submissions_per_month: 300
    max_submissions: 300
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: Institution name
        description: Institution name
        type: text
        required: false
      - name: Background
        description: What's your primary area of expertise (machine learning, chemical engineering, something else?)
        type: text
        required: false
      - name: Code URL
        description: Link to code (if available)
        type: text
        required: false
      - name: Was only ODAC23 data used for training?
        description: Answer "No" if you used any external data for training
        type: radio
        options: ["Yes", "No"]
        required: true
      - name: Training / Inference Time
        description: How long does it take to train your model and generate predictions?
        type: text
        required: false
      - name: Is force being modeled as a conservative vector field?
        description: That is, as a function of the gradient of potential energy
        type: radio
        options: ["Yes", "No"]
        required: false
      - name: Features
        description: If you used any hand-designed features, briefly describe them
        type: text
        required: false
      - name: What was the dataset size used for training?
        description: (all frames or something else?)
        type: text
        required: false
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: True
    allowed_submission_file_types: ".npz"
  - id: 2
    name: Predicting energy and forces from structure (S2EF) -- Test
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: False
    start_date: 2023-11-29 00:00:00
    end_date: 2042-12-31 23:59:59
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: s2ef_test
    max_submissions_per_day: 10
    max_submissions_per_month: 10
    max_submissions: 10
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: Institution name
        description: Institution name
        type: text
        required: false
      - name: Background
        description: What's your primary area of expertise (machine learning, chemical engineering, something else?)
        type: text
        required: false
      - name: Code URL
        description: Link to code (if available)
        type: text
        required: false
      - name: Was only ODAC23 data used for training?
        description: Answer "No" if you used any external data for training
        type: radio
        options: ["Yes", "No"]
        required: true
      - name: Training / Inference Time
        description: How long does it take to train your model and generate predictions?
        type: text
        required: false
      - name: Is force being modeled as a conservative vector field?
        description: That is, as a function of the gradient of potential energy
        type: radio
        options: ["Yes", "No"]
        required: false
      - name: Features
        description: If you used any hand-designed features, briefly describe them
        type: text
        required: false
      - name: What was the dataset size used for training?
        description: (all frames or something else?)
        type: text
        required: false
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: True
    allowed_submission_file_types: ".npz"
  - id: 3
    name: Predicting relaxed state energy from initial structure (IS2RE) -- Validation
    description: templates/challenge_phase_1_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: False
    start_date: 2023-11-29 00:00:00
    end_date: 2042-12-31 23:59:59
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: is2re_val
    max_submissions_per_day: 10
    max_submissions_per_month: 300
    max_submissions: 300
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: Institution name
        description: Institution name
        type: text
        required: false
      - name: Background
        description: What's your primary area of expertise (machine learning, chemical engineering, something else?)
        type: text
        required: false
      - name: Code URL
        description: Link to code (if available)
        type: text
        required: false
      - name: Was only ODAC23 data used for training?
        description: Answer "No" if you used any external data for training
        type: radio
        options: ["Yes", "No"]
        required: true
      - name: Training / Inference Time
        description: How long does it take to train your model and generate predictions?
        type: text
        required: false
      - name: Features
        description: If you used any hand-designed features, briefly describe them
        type: text
        required: false
      - name: What was the dataset size used for training?
        description: (all trajectories or something else?)
        type: text
        required: false
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: True
    allowed_submission_file_types: ".npz"
  - id: 4
    name: Predicting relaxed state energy from initial structure (IS2RE) -- Test
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: False
    start_date: 2023-11-29 00:00:00
    end_date: 2042-12-31 23:59:59
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: is2re_test
    max_submissions_per_day: 10
    max_submissions_per_month: 10
    max_submissions: 10
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: Institution name
        description: Institution name
        type: text
        required: false
      - name: Background
        description: What's your primary area of expertise (machine learning, chemical engineering, something else?)
        type: text
        required: false
      - name: Code URL
        description: Link to code (if available)
        type: text
        required: false
      - name: Was only ODAC23 data used for training?
        description: Answer "No" if you used any external data for training
        type: radio
        options: ["Yes", "No"]
        required: true
      - name: Training / Inference Time
        description: How long does it take to train your model and generate predictions?
        type: text
        required: false
      - name: Features
        description: If you used any hand-designed features, briefly describe them
        type: text
        required: false
      - name: What was the dataset size used for training?
        description: (all trajectories or something else?)
        type: text
        required: false
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: True
    allowed_submission_file_types: ".npz"

dataset_splits:
  - id: 1
    name: Intermediate state prediction -- val
    codename: intermediate_val
  - id: 2
    name: Intermediate state prediction -- test
    codename: intermediate_test
  - id: 3
    name: Relaxed state prediction -- val
    codename: relaxed_val
  - id: 4
    name: Relaxed state prediction -- test
    codename: relaxed_test

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 2
    leaderboard_decimal_precision: 4
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 2
    visibility: 3
    leaderboard_decimal_precision: 4
    is_leaderboard_order_descending: True
  - challenge_phase_id: 3
    leaderboard_id: 2
    dataset_split_id: 3
    visibility: 2
    leaderboard_decimal_precision: 4
    is_leaderboard_order_descending: True
  - challenge_phase_id: 4
    leaderboard_id: 2
    dataset_split_id: 4
    visibility: 3
    leaderboard_decimal_precision: 4
    is_leaderboard_order_descending: True
